{% set name = "patch" %}
{% set version = "1.16" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: c62073f356cff054c8ac24496f1a3d7cfa137835c31e9af39a9f5292fd75bd9f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - patch

about:
  home: https://github.com/techtonik/python-patch/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Cross-platform alternative to unix patch utility capable to apply unified diffs
  dev_url: https://github.com/techtonik/python-patch/

extra:
  recipe-maintainers:
    - windelbouwman
    - abloemert
