travis:
  secure:
    BINSTAR_TOKEN: EgIAG/9a7rJ2oDaa0oEgM4fFgt16Hmt8wf8ISKbCQVN/P72VhopYixZC9Nm4+iwRXleF6DvIh2+CAlY9eKQbjGSvaiTUcbtDFpPrRb58/LozFhXvxMAkxFBST4NP8oozXP5bmXNxSy5Fx2O1Iz07ugGnmjYuMjk3XkB8/o/pQnN1KV3zmAZ7/F5qsmA+iGqQOtPyptFgHsKFDRQkQYdHWNOkJMuEavkx07xZU8zYJSDLaeYjJSpENObx98Wcrsy36u5fV83el/I+1POsTuMu3hDC5Q6XxIQHSfHx3LldrUVXlMluQRzQsj7Kj/iGETKnahr8YLWQXpC2gYd5EJKWVgmq6t1Gc75NbLqxW17awi0Tjpz+ECX359P/NZN4G4OwboOfk2RdBcAUslsN/5wTxfycsncddJ5SvDoTYhYCjrx4Q6tSc5vOfcEblIjYQAXRT10KCcF/MhzP+bpr2nW75MAAy6YLhh/bqGTXMd/5w/X77nBIkbFo++t2YlUYgHGHzPUgAxOk17geHb3ZV0zD5lr9ysMrKFsPUEeVeb2V9dY833fFWCu6ny8xnVWuX17tggkmsHC3vy+xRbV3k9ALydlTNVESX4OaHXoTCumEhYyAuOddIRKqnEt5XQ5OA5LlGF7YpfXSUAjXZlb/lgrplwZr2i3ptU69CJ+Ws3mBUK8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
