travis:
  secure:
    BINSTAR_TOKEN: jUciEDWFEUhh7xfKZucvRaZz2JPN706FEEwgtMEylaUIUOa3PKp+a8yrbbChhhTv31m9VcA/Yxh9mba/XBT6JYQ8GoW7t8k39gkUngFcXu8GgPcPYnCT9WAZAzRXakOne6rtR14AI8iipAVOCHt8d5W1byOSgLsTDOi9rfL10vJrdUsyJGiP7660FqVkAGi//c4NVAidJbPE7gM8xN44fRY9EUBUnZ5IEqyCQKxssWCtUYmgspcmCWBhy+C8y+af+Yli7rBnOy4EYFbQYt/Buh5TjGakL3pC+6AGezxWEFBNA3YDxui4wXJt531MUaW0EQGxhxa1UQMJzhlO5Mr/jKCi9fkhqrV7k38H7OW6Tpa+EGzMoR7SVhzVf0jkvdinRzXuqgQv5+0IraxAQZATCcLVPSc6fmTmOJMwxoSQdSNlEWuwwOaG/0USlDjcdbSz6ntYyiVQPSaDWUI/FZFUBBbgcPekEceXFy19qVGkKZaYwXpijqPsOLOOHThIwFImnP9G8wbLEydpDFZ7gdrWlo0UVxqCC3y7V22xIRbyIh+9VoT2hRDAcCiD6qkaCled8qBdvYujdB+DhItWxtDKTGwTjDw8p4wJMT9n5swoWs5W0A1aAB86JK3JDEzoO1XNHD0k7loGlvYxwZgDo9wW+DJz6ZtNZf7Lipxabu5D3f8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
